apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendd
  name: frontendd
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 172.17.0.202
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontendd
  sessionAffinity: None
  type: LoadBalancer

